image:
  name: alpine/terragrunt:latest
  entrypoint: [""]

stages:
  - init
  - validate
  - plan
  - apply_staging
  - apply_production

variables:
  TF_IN_AUTOMATION: "true"
  TG_DOWNLOAD_DIR: "$CI_PROJECT_DIR/.terragrunt-cache"

cache:
  key: terraform-providers
  paths:
    - .terragrunt-cache/

init:
  stage: init
  script:
    - |
      set -eu
      for environment in staging; do
        echo "Init ${environment}"

        terragrunt run --all \
          --working-dir "${environment}" \
          --non-interactive \
          init
      done

validate:
  stage: validate
  script:
    - |
      set -eu
      for environment in staging; do 
        echo "Validating ${environment}"

        terragrunt run --all \
        --working-dir "${environment}" \
        --non-interactive \
        validate
      done

plan_staging:
  stage: plan
  needs:
    - validate
  script:
    - |
      set -eu

      terragrunt plan --all \
        --working-dir staging \
        -out="$CI_PROJECT_DIR/staging.tfplan" \
      
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - staging.tfplan